oauth:
  naver:
    client_id: wxo1BZFKWHDc37EpRJa6
    client_secret_id: m8d1wUiuyD
    acces_token_uri: https://nid.naver.com/oauth2.0/token
    grant_type: authorization_code
    api_me_uri: https://openapi.naver.com/v1/nid/me